name: Syntax Check

on:
  push:
    branches:
      - phuc   # Chỉ kích hoạt khi push lên nhánh phuc
    paths:
      - '**.html'  # Đổi lại thành đuôi file mà bạn cần

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: phuc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: '**.html'  # Đổi lại thành đuôi file mà bạn cần
